package com.snopsys.lgrau.model;

import java.io.Serializable;

/**
 * Flight2010 definition.
 * 
 * This file was generated by Ignite Web Console (05/11/2019, 11:14)
 **/
public class Flight2010 implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for destCountryName. */
    private String destCountryName;

    /** Value for originCountryName. */
    private String originCountryName;

    /** Value for count. */
    private Integer count;

    /** Empty constructor. **/
    public Flight2010() {
        // No-op.
    }

    /** Full constructor. **/
    public Flight2010(String destCountryName,
        String originCountryName,
        Integer count) {
        this.destCountryName = destCountryName;
        this.originCountryName = originCountryName;
        this.count = count;
    }

    /**
     * Gets destCountryName
     * 
     * @return Value for destCountryName.
     **/
    public String getDestCountryName() {
        return destCountryName;
    }

    /**
     * Sets destCountryName
     * 
     * @param destCountryName New value for destCountryName.
     **/
    public void setDestCountryName(String destCountryName) {
        this.destCountryName = destCountryName;
    }

    /**
     * Gets originCountryName
     * 
     * @return Value for originCountryName.
     **/
    public String getOriginCountryName() {
        return originCountryName;
    }

    /**
     * Sets originCountryName
     * 
     * @param originCountryName New value for originCountryName.
     **/
    public void setOriginCountryName(String originCountryName) {
        this.originCountryName = originCountryName;
    }

    /**
     * Gets count
     * 
     * @return Value for count.
     **/
    public Integer getCount() {
        return count;
    }

    /**
     * Sets count
     * 
     * @param count New value for count.
     **/
    public void setCount(Integer count) {
        this.count = count;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Flight2010))
            return false;
        
        Flight2010 that = (Flight2010)o;

        if (destCountryName != null ? !destCountryName.equals(that.destCountryName) : that.destCountryName != null)
            return false;
        

        if (originCountryName != null ? !originCountryName.equals(that.originCountryName) : that.originCountryName != null)
            return false;
        

        if (count != null ? !count.equals(that.count) : that.count != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = destCountryName != null ? destCountryName.hashCode() : 0;

        res = 31 * res + (originCountryName != null ? originCountryName.hashCode() : 0);

        res = 31 * res + (count != null ? count.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Flight2010 [" + 
            "destCountryName=" + destCountryName + ", " + 
            "originCountryName=" + originCountryName + ", " + 
            "count=" + count +
        "]";
    }
}